//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadMilkman.Docx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MadMilkman.Docx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.openxmlformats.org/officeDocument/2006/relationships/aFChunk.
        /// </summary>
        internal static string AltChunkRelationshipType {
            get {
                return ResourceManager.GetString("AltChunkRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml.
        /// </summary>
        internal static string DocumentContentType {
            get {
                return ResourceManager.GetString("DocumentContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument.
        /// </summary>
        internal static string DocumentRelationshipType {
            get {
                return ResourceManager.GetString("DocumentRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml.
        /// </summary>
        internal static string FooterContentType {
            get {
                return ResourceManager.GetString("FooterContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer.
        /// </summary>
        internal static string FooterRelationshipType {
            get {
                return ResourceManager.GetString("FooterRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml.
        /// </summary>
        internal static string HeaderContentType {
            get {
                return ResourceManager.GetString("HeaderContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.openxmlformats.org/officeDocument/2006/relationships/header.
        /// </summary>
        internal static string HeaderRelationshipType {
            get {
                return ResourceManager.GetString("HeaderRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        internal static string HtmlContentType {
            get {
                return ResourceManager.GetString("HtmlContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.openxmlformats.org/wordprocessingml/2006/main.
        /// </summary>
        internal static string MainNamespace {
            get {
                return ResourceManager.GetString("MainNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.openxmlformats.org/officeDocument/2006/relationships.
        /// </summary>
        internal static string RelationshipsNamespace {
            get {
                return ResourceManager.GetString("RelationshipsNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/rtf.
        /// </summary>
        internal static string RtfContentType {
            get {
                return ResourceManager.GetString("RtfContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/xml.
        /// </summary>
        internal static string XmlContentType {
            get {
                return ResourceManager.GetString("XmlContentType", resourceCulture);
            }
        }
    }
}
